name: install
description: "set up and install dependencies"
runs:
  using: composite
  steps:
    - name: setup pnpm
      uses: pnpm/action-setup@v4
        with:
          version: 9
    
    - name: setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: install Dependencies
      run: |
        node -v 
        pnpm -v
        pnpm install